[WIP]メッセージ送信機能の実装
norika69/chat-space pull request #12
Opened 2016-11-28 05:16 UTC by norika69

## what
メッセージを送信できる
メッセージの本文が空の時保存されないようにする
保存できない理由をフラッシュメッセージで出す

##why
chat-spaceにてメッセージ送信を可能にするため

2016-11-28 06:46 UTC, hand12 reviewed
いくつかコメントしたのでご確認ください！

2016-11-28 06:46 UTC, hand12 commented on app/controllers/groups_controller.rb
> +    @messages = @group.messages
こちら、set_groupの中で定義されており、before_actionによりshowが呼ばれる前にset_groupメソッドが呼ばれ、@groupは定義されていますので、こちらの記述はなくて良さそうですね！

2016-11-28 06:46 UTC, hand12 commented on app/controllers/messages_controller.rb
> +    @group = Group.find(params[:id])
set_messageメソッドを定義しているのですが、実際にやっていることはgroupを@groupをセットしていますね。
名前を変更した方がいいですね！
また、せっかくこのメソッドを定義したのに呼び出す処理が書いていないので、呼び出す処理も書いてあげましょう！

2016-11-28 06:46 UTC, hand12 commented on app/controllers/messages_controller.rb
> +       redirect_to group_path(params[:id]),alert: @message.errors.full_messages[0]
redirect_toとrenderの違いを調べてみてください！

2016-11-28 06:46 UTC, hand12 commented on app/controllers/messages_controller.rb
> +  end
このプルリクでは使っていないアクションは今定義しなくて良さそうですね！
削除しておきましょう！

2016-11-28 06:46 UTC, hand12 commented on app/controllers/users_controller.rb
>  end
usersコントローラーも使っていないのであれば削除しましょう！

2016-11-28 06:46 UTC, hand12 commented on app/views/groups/edit.html.haml
>      = form_for(@group, html: {class: "edit_chat_group", id: ""}) do |f|
idなど指定していないのであれば、書かなくて大丈夫です。

2016-11-28 06:46 UTC, hand12 commented on app/views/groups/show.html.haml
> +    = render 'chat_left_group',object: current_user.groups
objectは、ファイル名と同じ名前の変数を用意し、指定した値をその変数の中にいれて部分テンプレートの中でも使うというものです。
これは他にもやり方があるかつ、変数名がわかりづらくなるので、部分テンプレートに変数を渡す違うやり方を調べてみてください！

2016-11-28 06:46 UTC, hand12 commented on app/views/groups/show.html.haml
> +        = @group.users
ここエラー起きてないですか？

2016-11-28 06:46 UTC, hand12 commented on app/views/groups/show.html.haml
> +        -@messages.each do |message|
-の後も半角スペース空けましょう！

2016-11-28 06:46 UTC, hand12 commented on app/views/groups/show.html.haml
> +        -@messages.each do |message|
うまく動いているのが確認できたら、今度はこちらを部分テンプレートにしてみましょう！
部分テンプレートの方が繰り返し処理は早いです。

2016-11-29 03:40 UTC, norika69 commented on app/controllers/messages_controller.rb
> +       redirect_to group_path(params[:id]),alert: @message.errors.full_messages[0]
redirect_toはコントローラーのアクションを通してビューファイルを表示します。
それに対し、renderは直接ビューファイルを返すので、rengerの方が早く通信ができます。
使い分けとしては、redirect_toはデータの追加、更新、削除するときに、rendarはただデータを取得して表示したいときに使います。

2016-11-29 03:41 UTC, norika69 commented on app/views/groups/show.html.haml
> +        = @group.users
修正しました。

2016-11-29 04:32 UTC, hc0208 requested changes

2016-11-29 04:32 UTC, hc070208 commented on app/controllers/messages_controller.rb
> +    @group = Group.find(params[:id])
全体的にインデントがおかしいので整えてあげるようにしましょう。

2016-11-29 04:32 UTC, hc070208 commented on app/views/groups/show.html.haml
> +          = form_for @message, :url => messages_path do |f|
url: messages_pathと書くことが多いです。

2016-11-29 04:32 UTC, hc070208 commented on app/views/groups/show.html.haml
> +            = f.hidden_field :user_id, :value => current_user.id
value: current_user.idと書くことが多いです。

2016-11-29 04:43 UTC, hc070208 commented
LGTM

2016-11-29 04:44 UTC, merged