[WIP]messageモデルのテスト
norika69/chat-space pull request #14
Opened 2016-11-29 07:33 UTC by norika69

## what
バリデーションに引っかからずに保存できる場合
バリデーションに引っかかり、保存できない場合

## why
プログラムが意図した通りに動くことを確かめる
バグがないことを確かめるため

2016-11-29 08:35 UTC, norika69 commented
ターミナル
![2016-11-29 17 34 44](https://cloud.githubusercontent.com/assets/22586860/20702205/39154028-b65a-11e6-9863-a91f6885cf60.png)

2016-11-29 08:39 UTC, hand12 reviewed
コメントしました！
確認お願いいたします！

2016-11-29 08:39 UTC, hand12 commented on spec/factories/messages.rb
> +    image                 "rururu-"
かわいらしいですね笑
ただ、テストの際はどんな文字が来ても大丈夫ということを担保するために、ランダムで文字列が生成されるfackerというgemを使いましょう！

2016-11-29 08:39 UTC, hand12 commented on spec/factories/messages.rb
> +    image                 "rururu-"
また、画像もテスト用に画像を送信してくれるメソッドがあるので、調べて実装してみてください！

2016-11-29 08:39 UTC, hand12 commented on spec/models/message_spec.rb
> +    end
itとndの中はインデント下げましょう！

2016-11-30 03:53 UTC, XX-maker370 reviewed
コメントしました！確認お願いします。
一点だけですが、もう少し良い書き方になりますので頑張っていきましょう。

2016-11-30 03:53 UTC, utr066 commented on spec/factories/messages.rb
> +    image             { fixture_file_upload Rails.root.join('spec', 'fixtures', 'dummy.jpg'), 'image/jpeg' }
pokemonの名前ですか、可愛いですね。これでランダムな文字を取ることが出来ますね。
fixture_file_uploadよく書けました。素晴らしいです！

2016-11-30 03:53 UTC, utr066 commented on spec/models/message_spec.rb
> +      end
テスト自体の動きとしてはokです。createアクションの中でvalidとinvalidの場合でテストをしているので、contextで場合分けしていきましょう！

2016-11-30 04:18 UTC, hc0208 requested changes

2016-11-30 04:18 UTC, hc070208 commented on spec/models/message_spec.rb
> +  end
インデントが見づらいので修正お願いいたします。

2016-11-30 04:21 UTC, merged